/// Central registry of bundled image asset paths — reference these instead
/// of typing raw strings so a typo becomes a compile-time error, not a
/// blank image at runtime.
///
/// Drop new files into `assets/images/` (declared as a folder in
/// pubspec.yaml, so no pubspec edit is needed) and add a constant here.
/// Resolution variants go in `assets/images/2.0x/` and `3.0x/` with the
/// same file name — Flutter picks the right one automatically.
class AppImages {
  const AppImages._();

  static const _base = 'assets/images';

  /// 1024×1024 brand mark (serif J on pine green, gold accent). Also the
  /// source for the launcher icons generated by flutter_launcher_icons.
  static const appIcon = '$_base/app_icon.png';

  /// Transparent-background variant used as the Android adaptive-icon
  /// foreground layer.
  static const appIconForeground = '$_base/app_icon_foreground.png';

  /// Animated GIF shown while search results are being fetched.
  static const loading = '$_base/loading.gif';
}
